const mongoose=require('mongoose')
const SlamBook = new mongoose.Schema({
    q1:{
        type:String,
        require:true,
        trim:true,
    },
    q2:{
        type:String,
        require:true,
        trim:true,
    },
    q3:{
        type:String,
        require:true,
        trim:true,
    },
    q4:{
        type:String,
        require:true,
        trim:true,
    },
    q5:{
        type:String,
        require:true,
        trim:true,
    },
    q6:{
        type:String,
        require:true,
        trim:true,
    },
    q7:{
        type:String,
        require:true,
        trim:true,
    },
    q8:{
        type:String,
        require:true,
        trim:true,
    },
    q9:{
        type:String,
        require:true,
        trim:true,
    },
    q10:{
        type:String,
        require:true,
        trim:true,
    },
    q11:{
        type:String,
        require:true,
        trim:true,
    },
    q12:{
        type:String,
        require:true,
        trim:true,
    },
    q13:{
        type:String,
        require:true,
        trim:true,
    },
    q14:{
        type:String,
        require:true,
        trim:true,
    },
    q15:{
        type:String,
        require:true,
        trim:true,
    },
  
 
},{ timestamps: true })
module.exports=mongoose.model("SlamBook",SlamBook)